### ISSUE TITLE
Correciones

### ISSUE THREAD

**Issue by AlvaroMartinFernandez** [4GeeksAcademy/spain-fs-pt-85-SM-Create-a-HTML5-form#1]
Te falta el cierre de un elemento HTML , haz el cierre y comprueba que se envia el formulario, si tienes problemas al encontrar el elemento html que no has cerrado me indicas, funciona bien por que chrome es inteligente y lo arregla pero puede que con otros navegadores no funcione.

**Comment by unduashe** [comment]
Hola, Álvaro: 

He estado revisando el código del proyecto de html forms (https://github.com/4GeeksAcademy/spain-fs-pt-85-SM-Create-a-HTML5-form) y creo que el tag que no se encontraba cerrado era el form. Si no es este indícamelo ya que no he encontrado otro que haya podido causar la anomalía. El formulario se encontraba cerrado por debajo del div footer para que funcionase el input de tipo submit que se encuentra en el footer pudiendo haber causado el fallo, ya se encuentra corregido. Gracias!
